### ISSUE TITLE
[Feature][SDK] Add YAML formatted data source for Transform

### ISSUE THREAD

**Issue by emptyOVO** [apache/inlong#11005]
### Description

* parent issue: #10796 
* Add parsing for data source types such as the following. And support the conversion of YAML format data to other types of structures.

```
sid: sid
packageID: pid
Persons:
  - data: value1
    habbies:
      - index: 1
        name: sing1
      - index: 2
        name: dance1
      - index: 3
        name: rap1
  - data: value2
    habbies:
      - index: 1
        name: sing2
      - index: 2
        name: dance2
      - index: 3
        name: rap2
```

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
